# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 16:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20171208_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(22, message='\u5e74\u9f84\u5fc5\u987b\u572822\u5c81\u4ee5\u4e0a'), django.core.validators.MaxValueValidator(60, message='\u5e74\u9f84\u5fc5\u987b\u572860\u5c81\u4ee5\u4e0b')], verbose_name='\u5e74\u9f84'),
        ),
    ]
