# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_auto_20171203_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default=' ', max_length=50, verbose_name='\u6635\u79f0'),
        ),
    ]
