# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='learn_times',
            new_name='learn_time',
        ),
    ]
