# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prompt',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bfe\u7a0b\u63d0\u793a'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=100, verbose_name='\u5b66\u4f1a\u4ec0\u4e48'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.Lesson', verbose_name='\u7ae0\u8282'),
        ),
    ]
