# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20171210_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
