# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20171215_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u8bfe\u7a0b\u662f\u5426\u8f6e\u64ad'),
        ),
    ]
